# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/cancro/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/cancro

PRODUCT_COPY_FILES += \
    vendor/xiaomi/cancro/proprietary/vendor/bin/fm_qsoc_patches:$(TARGET_COPY_OUT_VENDOR)/bin/fm_qsoc_patches \
    vendor/xiaomi/cancro/proprietary/vendor/firmware/bcm2079x-b5_firmware.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm2079x-b5_firmware.ncd \
    vendor/xiaomi/cancro/proprietary/vendor/firmware/bcm2079x-b5_pre_firmware.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm2079x-b5_pre_firmware.ncd \
    vendor/xiaomi/cancro/proprietary/vendor/lib/libsensors.msm8974.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensors.msm8974.so
